version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:////data/coursework.db
    volumes:
      - ./data:/data
    depends_on:
      - db

  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./data:/root/db
      - ./sql:/sql
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
