default: install server

install:
  poetry update

test:
  poetry run pytest --maxfail=1 --disable-warnings -q

server:
  poetry run python server.py

server-alt:
  poetry run uvicorn app:app --host 0.0.0.0 --port 8000 --reload
